# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
url:              https://getbootstrap.com
baseurl:          /docs/3.4
encoding:         UTF-8
exclude:
  - assets/less/

plugins:
  - jekyll-sitemap

# Custom vars
title:            Bootstrap
description:      "The world's most popular mobile-first and responsive front-end framework."
current_version:  3.4.1
docs_version:     3.4
repo:             https://github.com/twbs/bootstrap
sass_repo:        https://github.com/twbs/bootstrap-sass

download:
  source:         https://github.com/twbs/bootstrap/archive/v3.4.1.zip
  dist:           https://github.com/twbs/bootstrap/releases/download/v3.4.1/bootstrap-3.4.1-dist.zip
  sass:           https://github.com/twbs/bootstrap-sass/archive/v3.4.1.tar.gz

blog:             https://blog.getbootstrap.com
expo:             https://expo.getbootstrap.com
themes:           https://themes.getbootstrap.com

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css
  css_hash:       "sha384-D2ZuGgDahkSohggw/ZMdhd53WLthg/9U5HnE5tLWq06ReSW7c5iH57+lJL0StuUQ"
  css_theme:      https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css
  css_theme_hash: "sha384-k4j5mOGo5q9ZDyWuKGoIE2Gqu/bpPfzyroN6O7n4n99J3Bwp6iS1Amr9w646qoyN"
  js:             https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js
  js_hash:        "sha384-8TqUaQwYLaXIyaHl68EdrK3QvCEgmVruFmApjk4dgbiLzZmBuZ4iSfS0kHuV9Ujk"
